export interface PointRecord {
  altitude: number
  cadence: number
  heartrate: number
  power: number
  speed: number
  time: number
  lon: number
  lat: number
}

export interface ActivityInfo {
  avg_cadence: number;
  avg_heartrate: number;
  avg_speed: number;
  avg_wheel_rpm: number;
  cadence_source: number;
  calories: number;
  category: number;
  client_id: number;
  comment_count: number;
  create_time: number;
  credits: number;
  deleted: boolean
  desc: string
  distance: number;
  down_avg_speed: number;
  down_distance: number;
  down_duration: number;
  duration: number;
  elevation_gain: number;
  elevation_loss: number;
  encoding_points: string
  end_cadence: number;
  end_time: number;
  end_wheel: number;
  extra_time: number;
  flat_avg_speed: number;
  flat_distance: number;
  flat_duration: number;
  heart_source: number;
  hidden: boolean
  is_export: number;
  is_like: number;
  is_valid: number;
  like_count: number;
  loc_source: number;
  map_hidden: number;
  map_id: number;
  max_altitude: number;
  max_cadence: number;
  max_grade: number;
  max_heartrate: number;
  max_speed: number;
  max_wheel_rpm: number;
  merge_record: string
  min_grade: number;
  modify_time: number;
  offset_lat: number;
  offset_lng: number;
  original_distance: number;
  original_duration: number;
  pic_url: string
  poi: string
  point_counts: number;
  powerAvg: number;
  powerFTP: number;
  powerIF: number;
  powerMax: number;
  powerNP: number;
  powerSource: number;
  powerTSS: number;
  powerVI: number;
  segment_index: string
  sport: number;
  sport_change_count: number;
  start_cadence: number;
  start_time: number;
  start_wheel: number;
  step: number;
  threed_workout: string
  thumbnail: string
  title: string
  up_avg_speed: number;
  up_distance: number;
  up_duration: number;
  upload_time: string
  user: number;
  user_name: string
  uuid: string
  workout_id: number;
}

export interface BlackbirdResponse {
  content: {
    avgPace: string;
    calories: string;
    distance: string;
    duration: string;
    endTime: number
    maxPace: string
    pace: string;
    score: string;
    startTime: number;
    sumHeight: string;
    sumHeightDistance: string;
    sumHeightTime: string;
    track: string;
  };
  func: string;
  msg: string;
  pageSize: number;
  pageTotal: number;
  status: string;
}
